sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install coveralls
- cp travis-ci/manage.py manage.py
script:
- pycodestyle saferecipient/
- python -m compileall saferecipient/
- coverage run --source=saferecipient/ manage.py test saferecipient
after_success:
- coveralls
before_deploy:
- find saferecipient/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > saferecipient/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: aQ8s9BNOZP9fFfjTeqLnVAokVF0tzHQAg7oO2pdNFDYHpEusTw5RF2X30Z83li5rdSyq8kHKHZryH+NcYJutV9w5WGZi/9IZWwtDQOn0A4F4A5aL57MjmgH3NJ9VTbz9J1wILM6kwvu16DdEiNGNK+sCkQ5LJXHq6RnAfD2dLGw=
  on:
    tags: true
    python: '3.6'
